#!/usr/bin/env bash

set -eu

case "$REQUEST_METHOD" in
    GET)
        case "$1" in
            hello)
                if [ -v QUERY_NAME ]; then
                    echo "Hello, $QUERY_NAME"
                else
                    echo "Hello, world"
                fi
                exit 0
            ;;
        esac
    ;;
esac

echo "Not found"
exit 404
