#!/usr/bin/env bash

file="$1"; shift

echo "$REQUEST_METHOD '$REQUEST_URI' from '$REMOTE_ADDR'" >&2

fullfile="$(dirname "$(realpath "$0")")/$file"
if [ -d "$fullfile" ]; then
    if [ -f "$fullfile/index.html" ]; then
        cat "$fullfile/index.html"
    else
        ls -1 "$fullfile" | while read line; do
            echo '<a href="$file">$file</a><br>'
        done
    fi
elif [ -x "$fullfile" ]; then
    . "$fullfile"
else
    cat "$fullfile"
    # echo "'$exepath' is not a executable file"
fi
