name: CI/Release

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          body: "This PR updates the generated code."
          branch: "chore/codegen-update"
          base: ${{ github.head_ref || github.ref_name }}

      - name: Run CI
        run: mise run ci

      - name: Build
        run: mise run build

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} ncgi --generate-notes --title ${{ github.ref_name }}
